[package]
name = "pulqva-desktop"
version = "0.0.0"
edition = "2024"
rust-version = "1.91"
publish = false
build = "build.rs"

[workspace]

[dependencies]
pulqva-core = { path = "../../../crates/pulqva-core" }
pulqva-privacy = { path = "../../../crates/pulqva-privacy" }
serde = { version = "1", features = ["derive"] }
same-file = "1"
sha2 = "0.10"
zip = { version = "=2.4.2", default-features = false, features = ["deflate"] }
tar = { version = "=0.4.44", default-features = false }
xz2 = { version = "=0.1.7", features = ["static"] }
tauri = { version = "=2.11.6" }

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }
